// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bootstrap_individual
NumericMatrix bootstrap_individual(int B, Eigen::VectorXd epsilon_hat, Eigen::MatrixXd X, Eigen::MatrixXd W_hat, Eigen::MatrixXd S_hat_sqrt_inverse);
RcppExport SEXP _graCRR_bootstrap_individual(SEXP BSEXP, SEXP epsilon_hatSEXP, SEXP XSEXP, SEXP W_hatSEXP, SEXP S_hat_sqrt_inverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type epsilon_hat(epsilon_hatSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type W_hat(W_hatSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type S_hat_sqrt_inverse(S_hat_sqrt_inverseSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_individual(B, epsilon_hat, X, W_hat, S_hat_sqrt_inverse));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP LFabs(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_graCRR_bootstrap_individual", (DL_FUNC) &_graCRR_bootstrap_individual, 5},
    {"LFabs", (DL_FUNC) &LFabs, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_graCRR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
