# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bootstrap_individual <- function(B, epsilon_hat, X, W_hat, S_hat_sqrt_inverse) {
    .Call(`_graCRR_bootstrap_individual`, B, epsilon_hat, X, W_hat, S_hat_sqrt_inverse)
}

